### ISSUE TITLE
BUG: utils/synth_data.py fails, blocking linkcheck job from completing successfully

### ISSUE THREAD

**Issue by pllim** [astropy/specreduce#230]
```
specreduce/utils/synth_data.py:docstring of specreduce.utils.synth_data.make_2d_arc_image:93: WARNING: Exception occurred in plotting specreduce-utils-synth_data-make_2d_arc_image-2
 from specreduce/docs/api/specreduce.utils.synth_data.make_2d_arc_image.rst:
Traceback (most recent call last):
  File "matplotlib/sphinxext/plot_directive.py", line 552, in _run_code
    exec(code, ns)
  File "<string>", line 2, in <module>
  File "specreduce/utils/synth_data.py", line 290, in make_2d_arc_image
    linelist = load_pypeit_calibration_lines(linelists, wave_air=wave_air)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "specreduce/calibration_data.py", line 288, in load_pypeit_calibration_lines
    linelist['wavelength'] = vac_to_air(linelist['wavelength'])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "specutils/utils/wcs_utils.py", line 148, in vac_to_air
    refr = refraction_index(wavelength, method=method, co2=co2)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "specutils/utils/wcs_utils.py", line 103, in refraction_index
    if method != 'Griesen2006' and wavelength.min() < 200 * u.nm:
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "astropy/units/quantity.py", line 696, in __array_ufunc__
    raise e
  File "astropy/units/quantity.py", line 641, in __array_ufunc__
    converters, unit = converters_and_unit(function, method, *inputs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "astropy/units/quantity_helper/converters.py", line 199, in converters_and_unit
    raise UnitConversionError(
astropy.units.core.UnitConversionError: Can only apply 'greater' function to dimensionless quantities when other argument is not a quantity (unless the latter is all zero/infinity/nan). [docutils]
```

This should be fixed. It blocks linkcheck job from reporting green even though there are no broken links.

Example log: https://github.com/astropy/specreduce/actions/runs/11773113091/job/32789536754

**Comment by kecnry** [comment]
I believe this is a duplicate of #227

**Comment by pllim** [comment]
Yeah you are correct. Thanks.
